[build]
builder = "RAILPACK"
buildCommand = "python manage.py collectstatic --no-input"

[deploy]
preDeployCommand = "python manage.py migrate"
startCommand = "gunicorn kashwebsite.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
