# Generated by Django on 2026-06-27

from django.conf import settings
from django.db import migrations, models


def copy_existing_files_to_database(apps, schema_editor):
    portfolio_document = apps.get_model('portfolio', 'PortfolioDocument')
    for document in portfolio_document.objects.exclude(file=''):
        if document.file_data:
            continue

        path = settings.MEDIA_ROOT / str(document.file)
        if path.exists():
            document.file_data = path.read_bytes()
            document.save(update_fields=['file_data'])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodocument',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunPython(copy_existing_files_to_database, migrations.RunPython.noop),
    ]
